name: rest_api_client
description: Abstraction for communicating with REST API in flutter projects. Incorporates exception handling and jwt with refresh token authorization.
version: 2.1.8
repository: https://github.com/salihagic/rest_api_client

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^4.0.1
  crypto: ^3.0.3
  dio: ^5.2.1
  pretty_dio_logger: ^1.3.1
  storage_repository: ^1.1.10
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
