name: rest_api_client
description: Abstraction for communicating with REST API in flutter projects. Incorporates exception handling and jwt with refresh token authorization.
version: 2.2.24
repository: https://github.com/salihagic/rest_api_client

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  storage_repository: ^1.1.14